### ISSUE TITLE
Allow search field population script to be linted

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/profiles-db#53]
I mistakenly assumed that the JS engine in MongoDB did not support ES6. It turns out it does (https://docs.mongodb.com/manual/release-notes/3.2-javascript/).

This means we should not have the eslint exclusion directive in `scripts/populate-search-fields.js`. Removing this requires a number of errors to be fixed.

This probably doesn't need resolving as moving to elastic search may change when and how we do stuff.

**Comment by st3v3nhunt** [comment]
Repo is no longer maintained.
